services:
    mongo:
      container_name: mongo
      image: mongo:4.4.1-bionic
      restart: unless-stopped
#      environment:
#        - MONGO_INITDB_ROOT_USERNAME=ziv
#        - MONGO_INITDB_ROOT_PASSWORD=zivarzi88
#        - MONGO_INITDB_DATABASE=unifi
      volumes:
        - /home/ziv/docker-mounts/mongo/db:/data/db

        #- /home/ziv/docker-mounts/mongo/db/config:/data/configdb
        #- /home/ziv/docker-mounts/mongo/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
        - /home/ziv/docker-mounts/mongo/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      ports:
        - "27017:27017"

    unifi-network-application:
      image: lscr.io/linuxserver/unifi-network-application:latest
      container_name: unifi-network-application
#      depends_on: 
#        - mongo      
      environment:
        - PUID=1000
        - PGID=1000
        - TZ=Asia/Jerusalem
        - MONGO_USER=ziv
        - MONGO_PASS=zivarzi88
        - MONGO_HOST=mongo
        - MONGO_PORT=27017
        - MONGO_DBNAME=unifi
        - MEM_LIMIT=1024 #optional
        - MEM_STARTUP=1024 #optional
        - MONGO_TLS= #optional
        - MONGO_AUTHSOURCE= #optional
      volumes:
        - /home/ziv/docker-mounts/unifi:/config
      ports:
        - 8443:8443
        - 3478:3478/udp
        - 10001:10001/udp
        - 8080:8043
#        - 1900:1900/udp #optional
        - 8843:8843 #optional
        - 8880:8880 #optional
        - 6789:6789 #optional
        - 5514:5514/udp #optional
      restart: unless-stopped        
